### ISSUE TITLE
Revisit architecture

### ISSUE THREAD

**Issue by tsargent** [namely/styleguide#242]
In order to speed up development, let's consider building all components as standalone, installable node modules.  If each component lives in its own github repository, is independently tested and published to npm.   HCM can begin to use these components as soon as they become available.  We can then begin to rebuild Namely-UI in its own repo and use these components as dependencies.  We could separate the css as well.  

I would like to research this pretty extensively so that we will know what this process will look like from beginning to end.

Inspiration:
https://lodash.com/
http://www.basscss.com/

Questions:

1. Can we avoid using gulp in each package?  It seems like something like `browserify ./src/entry.js -o  bundle.js` or whatever should suffice (with appropriate babel option, etc).  Not convinced? @jasonfellows found a good read on avoiding gulp: https://medium.com/@housecor/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.rwmem7cel

**Comment by jasonfellows** [comment]
I think it's important for these components to be available for export as separate modules. The enduser (payroll, hcm, arch. services) could use something like `import { DateField, NumberField } from 'namely-ui'`.

Does the case where an internal Namely application wants to use a minority of UI components in the package exist? This is an internal productivity tool, not a public lib. Even if we also provide a package that includes the entire UI by listing every component in package.json as dependencies, there is still the matter of maintaining tons of nearly identical package and build config files if we go that route.

It works with basscss because there is no build required for each package. It's just css, so there are no package dependencies. That is also a public lib with many more use cases. Our package config is still changing all the time.

We can reduce barriers to production by fixing the configuration of a single package and removing all UI-related files (namely-ui.scss) from the HCM app that are not imported via npm package.

**Comment by jasonfellows** [comment]
I'm all for removing Gulp. Why have a dozen dependencies that we don't need. That article convinced me on the train ride over this morning.

**Comment by jasonfellows** [comment]
If we could automate building a package for each component post-babel with a script built around `npm init`, then I could see offering multiple packages working, actually.

**Comment by jasonfellows** [comment]
https://github.com/namely/styleguide/pull/243

**Comment by tsargent** [comment]
@jasonfellows why are you closing this?

**Comment by jasonfellows** [comment]
We just revisited, voted on, and merged an architecture.

**Comment by tsargent** [comment]
LOL

**Comment by tsargent** [comment]
ok makes sense now after talking.
